version: "2"
services:
  needmorelumber:
    depends_on:
      - mongo
    container_name: needmorelumber
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/node_app/app
    working_dir: /opt/node_app/app
    command: ['yarn', 'start']
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
