version: 2.1

orbs:
  node: circleci/node@1.0.0

jobs:
  build-and-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # TODO: see how useful this is.
      - node/with-cache:
          cache-key: "yarn.lock"
          steps:
            - run: "yarn"
      - run: "yarn run lint"

workflows:
  version: 2.1
  build-and-lint:
    jobs:
      - build-and-lint
