version: 2.1

orbs:
  node: circleci/node@1.0.0

jobs:
  - build-and-lint:
      steps:
        # TODO: see how useful this is.
        - node/with-cache:
            cache-key: "yarn.lock"
            steps:
              - run: "yarn"
        - run: "yarn run lint"

