version: 2.1

orbs:
  node: circleci/node@1.0.0

workflows:
  test:
    jobs:
      - build-and-lint:
          steps:
            - node/with-cache:
                cache-key: "yarn.lock"
                steps:
                  - run: "yarn"
            - run: "yarn run lint"

